[server.pv.addon.discs.error]
erase_wrong_item = "&cCan't erase this item"
get_track_fail = "&cFailed to get the track: %s"
search_fail = "&cFailed to get the search result: %s"
not_a_record = "&cYou need have a record in your hand to burn it"
not_burnable = "&cThis record is not burnable"
unknown_subcommand = "&cUnknown subcommand. Available commands: %s"
no_permission = "&cNo permission"

[server.pv.addon.discs.usage]
burn = "&cUsage: /discs burn <url> [label]"

[server.pv.addon.discs.arg]
url = "<url>"
label = "[label]"
search = "<search>"

[server.pv.addon.discs.actionbar]
track_not_found = "Track not found: %s"
playing = "Now playing: %s"
loading = "Loading..."

[server.pv.addon.discs.success]
erase = "&aCustom audio erased"
burn = "&aDisc burned. Label: %s"

[server.pv.addon.discs.format]
search_entry = "&e%1$s &7by %2$s"

[client.pv.activation]
discs = "Discs"
